### PR TITLE
Fixed rendering of http_response

### PR DESCRIPTION
**Pull request by henhuy**
Related to #25

### CODE REVIEW

**Comment by meeb** [comment]
The render is already called here:

https://github.com/meeb/django-distill/blob/master/django_distill/renderer.py#L138

Calling it blindly in your patch isn't a good idea, not all responses can be rendered so your patch would introduce more issues. I would need to see your view before I could comment on why you are getting an error you mention in issue #25 - are you not returning a template-like object?

**Comment by henhuy** [comment]
You are right! Rendering is skipped in my code, as my response is just a `Response` of type `application/json` with renderer `JSONRenderer` - as I want to distill a `ListAPIView` from rest-framework...
But couldn't that be a valid feature to support this kind of views?
I will try for myself - maybe fork...

**Comment by meeb** [comment]
`django.http.HttpResponse` class doesn't have a `render()` method so this will also introduce errors. I'll need to check the Django internals to see if there's a sane way to check for this easily.

**Comment by henhuy** [comment]
Yes, I also stumpled upon `HttpResponse` not having `render` function...
I checked code again:
`rest-framework.response.Response` inherits `django.tempate.response.SimpleTemplateResponse` - maybe you could check for this class, instead of `TemplateResponse` (`TEmplateResponse itself is also inherits from `SimpleTemplateResponse`)?!

**Comment by meeb** [comment]
Sure, after some checking of the code your suggestion is reasonable. I've just pushed a change where `distill` checks objects returned by views are children of `SimpleTemplateResponse` and not `TemplateResponse` which will do what you want. I'll push this in the next release. Given this closes this issue I won't merge your PR but the fix is similar anyway. Thanks for the contribution.

**Pull request closed without merging**
