### PR TITLE
Optional static and media copying while distill-local

### LINKED ISSUE #28: Make copying of existing staticfiles and media optional
In my case, I want to serve distilled files as static files via Whitenoise.
Therefore I store disitilled files in my `STATIC_ROOT`.
Unfortunately, `django-distill` copies all existing staticfiles and media files into subfolder `static` in `DISTILL_DIR` when running `distill-local` - and thus all files are copied unnecessarily.

I created a PR in which copying of staticfiles and media can be suppressed by giving an extra option `--exclude-staticfiles`. Maybe this is also helpful for others?
See my branch https://github.com/henhuy/django-distill/tree/optional_static_and_media

### PR DESCRIPTION
**Pull request by henhuy**
Closes #28

### CODE REVIEW

**Comment by meeb** [comment]
I'm still considering this request to decide if it's a good idea as I'm not entirely convinced it's a sensible use case, however there are a couple of immediate issues with the PR if it were to be merged in its current state. If there were to be an `--exclude-staticfiles` flag it needs to be replicated on all 3 `distill-*` commands and have a tests. Additionally hacking the `copy_static_and_media_files()` call into the command handler and out of the renderer class might be a bit messy.

**Comment by henhuy** [comment]
you are right - Didn't pay attention to the other `distill-*` commands.
Considering the renderer class: As `copy_static` itself is a staticmethod and thus independent of class and only used in `collectstatic`, I thougt it makes sense to move it up as module class...

**Comment by meeb** [comment]
Thanks for the contribution. I've merged your PR, but I'll post-merge tweak it such as adding in support for the other `distill_*` commands.

**Comment by henhuy** [comment]
Nice - thank you!

**Comment by meeb** [comment]
No problem. Your slightly modified PR along with some new tests are in the 2.2 release I've just pushed to PyPI.

**Pull request merged**
